import pygame

DRIVE_CAR_EVENT = pygame.USEREVENT + 1
RESET_CAR_EVENT = pygame.USEREVENT + 2
USER_QUIT = pygame.USEREVENT + 3
TEXT_BOX_INPUT = pygame.USEREVENT + 4
BUTTON_CLICK = pygame.USEREVENT + 5
START_RACE_EVENT = pygame.USEREVENT + 6
SUBMIT_SCORE_EVENT = pygame.USEREVENT + 7
